In [2]:
import pandas as pd

In [3]:
allele_table_a3026 = pd.read_csv('/syn1/liangzhen/jinhua_jilab_project/result/DNA_Amplicon/trees/a3026_allele_table_raw.csv',header=0,index_col=0,na_filter=False)
allele_table_a3028 = pd.read_csv('/syn1/liangzhen/jinhua_jilab_project/result/DNA_Amplicon/trees/a3028_allele_table_raw.csv',header=0,index_col=0,na_filter=False)
allele_table_a3030 = pd.read_csv('/syn1/liangzhen/jinhua_jilab_project/result/DNA_Amplicon/trees/a3030_allele_table_raw.csv',header=0,index_col=0,na_filter=False)

In [4]:
allele_table = pd.concat([allele_table_a3026,allele_table_a3028,allele_table_a3030],axis=0)

In [7]:
allele_table

,Sample,cellBC,intBC,r1,allele,readCount,UMI,UMI_ratio
817144,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Tpt1,None,None,5648,967,0.967000
285858,T1_a3026,T1_a3026_GCATCGGCATCATCCC,Rpl39,None,None,3998,897,0.944211
921302,T3_a3026_2_1,T3_a3026_2_1_CAAGGGAGTCCACTCT,Tpt1,None,None,5153,856,0.978286
821869,T3_a3026_1_1,T3_a3026_1_1_GAAATGACATCGGATT,Tpt1,None,None,5022,850,0.977011
836828,T3_a3026_1_1,T3_a3026_1_1_GTGGAAGGTTGGGACA,Tpt1,None,None,5022,849,0.973624
...,...,...,...,...,...,...,...,...
1102032,T3_a3030_2_1,T3_a3030_2_1_TTTGATCTCTCCCAAC,Fth1,None,None,6,2,0.133333
1102241,T3_a3030_2_1,T3_a3030_2_1_TTTGGTTGTCGTCAGC,Tpt1,93:1I,93:1I,6,2,0.008772
1102261,T3_a3030_2_1,T3_a3030_2_1_TTTGGTTGTGACATCT,Hint1,None,None,6,2,0.100000
1102423,T3_a3030_2_1,T3_a3030_2_1_TTTGTTGCACGGTGTC,Tpt1,93:4D,93:4D,6,2,0.008299
1102508,T3_a3030_2_1,T3_a3030_2_1_TTTGTTGTCGGTATGT,Tpt1,92:1D,92:1D,6,2,0.008772

In [6]:
cell_lineage = pd.read_csv('/syn1/liangzhen/jinhua_jilab_project/result/DNA_Amplicon/cell_lineage.csv',sep=',')
cell_lineage

      lineageGrp                         cellBC
0             C1    T2_a3028_2_TGGTAGTGTCTGTGTA
1             C1  T3_a3026_2_1_GAAGCGATCGAGTGGA
2             C1    T2_a3028_2_ATCCTATAGCACGATG
3             C1  T3_a3028_1_1_ATCCTATTCTCGGCTT
4             C1    T2_a3028_2_TGTAGACAGCACCCAC
...          ...                            ...
46166       C173      T1_a3028_TCCGGGATCAGTGTGT
46167       C173      T1_a3028_GTCTACCCAGGTATGG
46168       C173      T1_a3028_ATTGGGTAGTTACGGG
46169       C173      T1_a3028_CCTGCATGTGTCTAAC
46170       C173      T1_a3026_CTGTACCAGTCCTGTA

[46171 rows x 2 columns]

In [8]:
allele_table = pd.merge(allele_table,cell_lineage,on=['cellBC'],how='inner')

In [9]:
allele_table

,Sample,cellBC,intBC,r1,allele,readCount,UMI,UMI_ratio,lineageGrp
0,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Tpt1,None,None,5648,967,0.967000,C9
1,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Btf3,None,None,827,96,0.989691,C9
2,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Calm2,None,None,3075,88,0.897959,C9
3,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Hint1,None,None,624,70,0.958904,C9
4,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Slc25a3,None,None,882,64,1.000000,C9
...,...,...,...,...,...,...,...,...,...
1131525,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Tpt1,None,None,12,3,0.300000,C120
1131526,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Calr,81:2D,81:2D,165,2,0.500000,C120
1131527,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Tpt1,93:1I,93:1I,13,2,0.200000,C120
1131528,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Rpl39,None,None,7,2,0.666667,C120
1131529,T1_a3030,T1_a3030_AAGTGAACAGGATCTT,Rpl39,None,None,20,4,1.000000,C7

In [10]:
gene_names = ['Acta1', 'Hsp90b1','Calr','Cfl1','Myl6','Rpl39','Calm2','Fth1','Hsp90ab1','Tpt1','Slc25a3','Lgals1','Btf3','Hint1','Calm1']

In [11]:
allele_table['gene_r1'] = allele_table['intBC'] + '_' + allele_table['r1']
allele_table

,Sample,cellBC,intBC,r1,allele,readCount,UMI,UMI_ratio,lineageGrp,gene_r1
0,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Tpt1,None,None,5648,967,0.967000,C9,Tpt1_None
1,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Btf3,None,None,827,96,0.989691,C9,Btf3_None
2,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Calm2,None,None,3075,88,0.897959,C9,Calm2_None
3,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Hint1,None,None,624,70,0.958904,C9,Hint1_None
4,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Slc25a3,None,None,882,64,1.000000,C9,Slc25a3_None
...,...,...,...,...,...,...,...,...,...,...
1131525,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Tpt1,None,None,12,3,0.300000,C120,Tpt1_None
1131526,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Calr,81:2D,81:2D,165,2,0.500000,C120,Calr_81:2D
1131527,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Tpt1,93:1I,93:1I,13,2,0.200000,C120,Tpt1_93:1I
1131528,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Rpl39,None,None,7,2,0.666667,C120,Rpl39_None
1131529,T1_a3030,T1_a3030_AAGTGAACAGGATCTT,Rpl39,None,None,20,4,1.000000,C7,Rpl39_None

In [12]:
allele_table_mut = allele_table[allele_table['r1']!='None']
allele_table_mut

,Sample,cellBC,intBC,r1,allele,readCount,UMI,UMI_ratio,lineageGrp,gene_r1
5,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Rpl39,88:3D,88:3D,289,61,0.398693,C9,Rpl39_88:3D
6,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Rpl39,87:4D,87:4D,228,53,0.346405,C9,Rpl39_87:4D
8,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Myl6,84:9D,84:9D,315,38,0.481013,C9,Myl6_84:9D
10,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Myl6,90:2D,90:2D,271,28,0.354430,C9,Myl6_90:2D
12,T3_a3026_1_1,T3_a3026_1_1_CTACCCAAGGGCTTCC,Hsp90ab1,87:1D,87:1D,139,21,0.656250,C9,Hsp90ab1_87:1D
...,...,...,...,...,...,...,...,...,...,...
1131522,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Tpt1,81:16D,81:16D,18,4,0.400000,C120,Tpt1_81:16D
1131523,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Fth1,89:16D,89:16D,18,3,0.500000,C120,Fth1_89:16D
1131524,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Fth1,90:1I,90:1I,13,3,0.500000,C120,Fth1_90:1I
1131526,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Calr,81:2D,81:2D,165,2,0.500000,C120,Calr_81:2D
1131527,T1_a3030,T1_a3030_CAGTTAGTCAAACCCA,Tpt1,93:1I,93:1I,13,2,0.200000,C120,Tpt1_93:1I

# T1

In [17]:
samples = ['T1_a3026','T1_a3028','T1_a3030']

In [18]:
allele_table_rep = allele_table[allele_table['Sample'].isin(samples)]
cell_mutation_matrix = pd.DataFrame(index=list(set(allele_table_rep['cellBC'])))
for gene in gene_names:
    print(gene)
    allele_table_gene = allele_table_rep[allele_table_rep['intBC']==gene]
    allele_table_gene = allele_table_gene[allele_table_gene['r1']!='None']
    df = allele_table_gene.pivot(index='cellBC', columns='r1', values='UMI')
    df= df.fillna(0)
    df[df > 0] = 1
    df.columns = [gene + '_' + indel for indel in df.columns]
    cell_mutation_matrix = cell_mutation_matrix.join(df, how='outer')
    cell_mutation_matrix = cell_mutation_matrix.fillna(0)

cell_lineage = pd.read_csv('/syn1/liangzhen/jinhua_jilab_project/result/DNA_Amplicon/cell_lineage.csv',header=0)
cell_lineage.index = cell_lineage.cellBC
cell_lineage = cell_lineage.loc[allele_table_rep.cellBC.unique(),:]

for lineageGrp in cell_lineage['lineageGrp'].unique():

    cell_mutation_matrix_lineageGrp = cell_mutation_matrix.loc[cell_lineage[cell_lineage['lineageGrp'].isin([lineageGrp])]['cellBC'],:]           
    cell_mutation_matrix_lineageGrp = cell_mutation_matrix_lineageGrp.astype(int)
    if cell_mutation_matrix_lineageGrp.shape[0] < 100:
        continue

    cell_mutation_matrix_lineageGrp = cell_mutation_matrix_lineageGrp.loc[:, (cell_mutation_matrix_lineageGrp != 0).any(axis=0)]
    if cell_mutation_matrix_lineageGrp.shape[1] == 0:
        continue
    cell_mutation_matrix_lineageGrp.loc['synthetic'] = [ 0 for i in range(0,cell_mutation_matrix_lineageGrp.shape[1])]

    cell_mutation_matrix_lineageGrp.to_csv('/syn1/liangzhen/jinhua_jilab_project/result/DNA_Amplicon/trees/merge_all_experiments/'+'T1/'+'cell_mutation_matrix-'+str(lineageGrp)+'-'+str(cell_mutation_matrix_lineageGrp.shape[0])+'.csv')

    cell_mutation_sequence = cell_mutation_matrix_lineageGrp.apply(lambda row: ''.join(row.astype(str)), axis=1)
    output_file = '/syn1/liangzhen/jinhua_jilab_project/result/DNA_Amplicon/trees/merge_all_experiments/'+'T1/'+ 'cell_mutation_matrix-'+str(lineageGrp)+'-'+str(cell_mutation_matrix_lineageGrp.shape[0])+'.phy'
    with open(output_file, 'w') as file:
        file.write(f"{cell_mutation_matrix_lineageGrp.shape[0]} \t{cell_mutation_matrix_lineageGrp.shape[1]}\n") 
        for index, line in cell_mutation_sequence.items():
            file.write(f"{index}\t{line}\n")

Acta1
Hsp90b1
Calr
Cfl1
Myl6
Rpl39
Calm2
Fth1
Hsp90ab1
Tpt1
Slc25a3
Lgals1
Btf3
Hint1
Calm1